[project]
name = "kulimweb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "grammar @ https://github.com/jake1104/KULIM/releases/download/0.1.0-rc.9/grammar-0.1.0rc9-cp312-cp312-linux_x86_64.whl",
    "hangul @ https://github.com/jake1104/KULIM/releases/download/0.1.0-rc.9/hangul-0.0.1-py3-none-any.whl",
    "kulim @ https://github.com/jake1104/KULIM/releases/download/0.1.0-rc.9/kulim-0.1.0rc9-py3-none-any.whl",
    "uvicorn>=0.38.0",
]
